apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: php-app-pod
  name: php-app-pod
spec:
  containers:
  - image: php_todo:0.2
    name: php-app-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
